### ISSUE TITLE
[Security] Workflow cache.yml is using vulnerable action jiro4989/setup-nim-action

### ISSUE THREAD

**Issue by qazaqstan2025** [awseward/call_status#156]
The workflow cache.yml is referencing action jiro4989/setup-nim-action using references v1.3.4. However this reference is missing the commit [50fd5aacd77e300dc122c5cb626403817fb466c7](https://github.com/jiro4989/setup-nim-action/commits/50fd5aacd77e300dc122c5cb626403817fb466c7) which may contain fix to the some vulnerability. 
The vulnerability fix that is missing by actions version could be related to: 
(1) CVE fix 
(2) upgrade of vulnerable dependency 
(3) fix to secret leak and others. 
Please consider to update the reference to the action.

**Comment by awseward** [comment]
Thanks for the heads up!
